

# §4-600 Months


MONTH_ABBREVIATIONS = {
    "January":   "Jan.",
    "February":  "Feb.",
    "March":     "Mar.",
    "April":     "Apr.",
    "May":       "May",
    "June":      "June",
    "July":      "July",
    "August":    "Aug.",
    "September": "Sept.",
    "October":   "Oct.",
    "November":  "Nov.",
    "December":  "Dec."
}

# §4-700 Frequently Cited Journals
JOURNAL_ABBREVIATIONS = {
    "Boston University Law Review":        "B.U. L. Rev.",
    "Buffalo Law Review":                  "Buff. L. Rev.",
    "California Law Review":               "Cal. L. Rev.",
    "Case Western Reserve Law Review":     "Case W. Res. L. Rev.",
    "Columbia Law Review":                 "Colum. L. Rev.",
    "Cornell Law Review":                  "Cornell L. Rev.",
    "Duke Law Journal":                    "Duke L.J.",
    "Fordham Law Review":                  "Fordham L. Rev.",
    "Georgetown Law Journal":              "Geo. L.J.",
    "George Washington Law Review":        "Geo. Wash. L. Rev.",
    "Harvard Law Review":                  "Harv. L. Rev.",
    "Howard Law Journal":                  "How. L.J.",
    "Michigan Law Review":                 "Mich. L. Rev.",
    "Minnesota Law Review":                "Minn. L. Rev.",
    "New York University Law Review":      "N.Y.U. L. Rev.",
    "Ohio State Law Journal":              "Ohio St. L.J.",
    "Rutgers Law Review":                  "Rutgers L. Rev.",
    "Seton Hall Law Review":               "Seton Hall L. Rev.",
    "Stanford Law Review":                 "Stan. L. Rev.",
    "Supreme Court Review":                "Sup. Ct. Rev.",
    "Temple Law Review":                   "Temp. L. Rev.",
    "Texas Law Review":                    "Tex. L. Rev.",
    "UCLA Law Review":                     "UCLA L. Rev.",
    "University of Chicago Law Review":    "U. Chi. L. Rev.",
    "University of Pennsylvania Law Review":"U. Pa. L. Rev.",
    "Vanderbilt Law Review":               "Vand. L. Rev.",
    "Virginia Law Review":                 "Va. L. Rev.",
    "Washington University Law Quarterly": "Wash. U. L.Q.",
    "Wisconsin Law Review":                "Wis. L. Rev.",
    "Yale Law Journal":                    "Yale L.J."
}

# ----- Full Allowed Reporters List -----
ALLOWED_REPORTERS = {
    "U.S.", "S. Ct.", "L. Ed.", "L. Ed. 2d", "F.", "F.2d", "F.3d", "F.4th",
    "F. Supp.", "F. Supp. 2d", "F. Supp. 3d", "F. App'x", "F.R.D.",
    "Fed. Cas.", "B.R.", "Fed. Cl.", "Ct. Cl.", "C.C.P.A.", "Cust. Ct.",
    "Ct. Int'l Trade", "C.I.T.", "T.C.", "T.C. Memo", "B.T.A.", "Vet. App.",
    "M.J.", "Cal.", "Cal. App.", "Cal. Rptr.", "N.Y.", "N.Y.S.", "N.Y.2d",
    "N.Y.3d", "Fla.", "Ill.", "Ill. App.", "Ala.", "So. 2d", "Ala. App.",
    "Alaska", "Ariz.", "Ark.", "Colo.", "Conn.", "Del.", "Ga.", "Haw.",
    "Idaho", "Ind.", "Iowa", "Kan.", "Ky.", "La.", "Me.", "Md.", "Mass.",
    "Mich.", "Minn.", "Miss.", "Mo.", "Mont.", "Neb.", "Nev.", "N.H.",
    "N.J.", "N.M.", "A.D.", "A.D.2d", "A.D.3d", "Misc.", "Misc. 2d",
    "Misc. 3d", "N.Y.S.2d", "N.Y.S.3d", "N.C.", "N.D.", "Ohio St.",
    "Ohio St. 2d", "Ohio St. 3d", "Okla.", "Or.", "Pa.", "R.I.", "S.C.",
    "S.D.", "Tenn.", "Tex.", "Tex. Crim.", "Utah", "Vt.", "Va.", "Wash.",
    "Wash. 2d", "W. Va.", "Wis.", "Wis. 2d", "Wyo.", "P.R.R.", "P.R. Dec.",
    "P.R. Offic. Trans.", "V.I.", "Guam", "N. Mar. I.", "Nav. R.", "I.L.R.",
    "M.P.R.", "C.M.A.", "C.M.R.", "N.L.R.B.", "U.S.P.Q.", "U.S.P.Q.2d",
    "I. & N. Dec.", "F.E.R.C.", "F.T.C.", "F.L.R.A.", "E.A.D.", "WI", "IL",
    "SD", "OH", "ME", "VT", "ND", "MP", "WL", "LEXIS", "NY Slip Op", "Dall.",
    "Cranch", "Wheat.", "Pet.", "How.", "Black", "Wall.", "Eng. Rep.",
    "K.B.", "Q.B.", "Ex.", "Ch.", "A.C.", "All E.R.", "W.L.R.", "I.C.J.",
    "P.C.I.J.", "E.C.H.R.", "Eur. Ct. H.R.", "E.C.R.", "E.C.J."
}

# ----- Court Reporter Mappings -----
COURT_REPORTER_MAPPING = {
    "Supreme Court": {"U.S.", "S. Ct.", "L. Ed.", "L. Ed. 2d"},
    "Court of Appeals": {"F.2d", "F.3d", "F.4th"},
    "District Courts": {"F. Supp.", "F. Supp. 2d", "F. Supp. 3d", "F.R.D."},
    "Court of Federal Claims": {"Ct. Cl."},
    "Tax Court": {"T.C.", "T.C. Memo"},
    "Bankruptcy Courts": {"B.R."},
    "Military Service": {"M.J."},
    "Veterans' Appeals": {"Vet. App."}
}

STATE_COURT_REPORTER_MAPPING = {
    "Alabama": {"Ala.", "So. 2d", "Ala. App."},
    "Alaska": {"Alaska"},
    "Arizona": {"Ariz."},
    "Arkansas": {"Ark."},
    "California": {"Cal.", "Cal. App.", "Cal. Rptr."},
    "Colorado": {"Colo."},
    "Connecticut": {"Conn."},
    "Delaware": {"Del."},
    "District of Columbia": {"D.C."},
    "Florida": {"Fla."},
    "Georgia": {"Ga."},
    "Hawaii": {"Haw."},
    "Idaho": {"Idaho"},
    "Illinois": {"Ill.", "Ill. App."},
    "Indiana": {"Ind."},
    "Iowa": {"Iowa"},
    "Kansas": {"Kan."},
    "Kentucky": {"Ky."},
    "Louisiana": {"La."},
    "Maine": {"Me."},
    "Maryland": {"Md."},
    "Massachusetts": {"Mass."},
    "Michigan": {"Mich."},
    "Minnesota": {"Minn."},
    "Mississippi": {"Miss."},
    "Missouri": {"Mo."},
    "Montana": {"Mont."},
    "Nebraska": {"Neb."},
    "Nevada": {"Nev."},
    "New Hampshire": {"N.H."},
    "New Jersey": {"N.J."},
    "New Mexico": {"N.M."},
    "New York": {"N.Y.", "N.Y.S.", "N.Y.2d", "N.Y.3d"},
    "North Carolina": {"N.C."},
    "North Dakota": {"N.D."},
    "Ohio": {"Ohio St."},
    "Oklahoma": {"Okla."},
    "Oregon": {"Or."},
    "Pennsylvania": {"Pa."},
    "Rhode Island": {"R.I."},
    "South Carolina": {"S.C."},
    "South Dakota": {"S.D."},
    "Tennessee": {"Tenn."},
    "Texas": {"Tex."},
    "Utah": {"Utah"},
    "Vermont": {"Vt."},
    "Virginia": {"Va."},
    "Washington": {"Wash."},
    "West Virginia": {"W. Va."},
    "Wisconsin": {"Wis."},
    "Wyoming": {"Wyo."}
}

# ----- Citation Signals -----
VALID_CITATION_SIGNALS = [
    "*see*", "*see also*", "*cf.*", "*but see*", "*compare*", "*accord*",
    "*contra*", "*but cf.*", "*see generally*", "*compare... with*", "*e.g.*"
]


CITATION_SIGNALS_ORDERED = [
    "e.g.,", "accord", "see", "see also", "cf.", "compare",
    "contra", "but see", "but cf.", "see generally"
]

# ----- Word Abbreviations (§4-100) -----
WORD_ABBREVIATIONS = {
    "Academic": "Acad.", "Academy": "Acad.", "Account": "Acct.", "Accounting": "Acct.",
    "Administrative": "Admin.", "Administration": "Admin.", "Administrator": "Adm'r",
    "Administratrix": "Adm'x", "Advertising": "Advert.", "Agriculture": "Agric.",
    "Alliance": "All.", "Alternative": "Alt.", "America": "Am.", "American": "Am.",
    "And": "&", "Associate": "Assoc.", "Association": "Ass’n", "Atlantic": "Atl.",
    "Authority": "Auth.", "Automobile": "Auto.", "Automotive": "Auto.", "Avenue": "Ave.",
    "Bankruptcy": "Bankr.", "Board": "Bd.", "Broadcast": "Broad.", "Broadcaster": "Broad.",
    "Broadcasting": "Broad.", "Brotherhood": "Bhd.", "Brothers": "Bros.", "Building": "Bldg.",
    "Business": "Bus.", "Capital": "Cap.", "Casualty": "Cas.", "Catholic": "Cath.",
    "Center": "Ctr.", "Centre": "Ctr.", "Central": "Cent.", "Chemical": "Chem.",
    "Children": "Child.", "Coalition": "Coal.", "College": "Coll.", "Commerce": "Com.",
    "Commercial": "Com.", "Commission": "Comm’n", "Commissioner": "Comm’r",
    "Committee": "Comm.", "Communication": "Commc’n", "Community": "Cmty.", "Company": "Co.",
    "Compensation": "Comp.", "Computer": "Comput.", "Condominium": "Condo.", "Congress": "Cong.",
    "Congressional": "Cong.", "Consolidated": "Consol.", "Construction": "Constr.",
    "Continental": "Cont’l", "Contract": "Cont.", "Contracting": "Cont.", "Cooperative": "Coop.",
    "Corporation": "Corp.", "Correction": "Corr.", "Correctional": "Corr.", "Corrections": "Corr.",
    "County": "Cnty.", "Defend": "Def.", "Defender": "Def.", "Defense": "Def.",
    "Department": "Dep’t", "Detention": "Det.", "Development": "Dev.", "Digital": "Dig.",
    "Director": "Dir.", "Distributor": "Distrib.", "Distributing": "Distrib.",
    "Distribution": "Distrib.", "District": "Dist.", "Division": "Div.", "Doctor": "Dr.",
    "East": "E.", "Eastern": "E.", "Economic": "Econ.", "Economical": "Econ.",
    "Economics": "Econ.", "Economy": "Econ.", "Education": "Educ.", "Educational": "Educ.",
    "Electric": "Elec.", "Electrical": "Elec.", "Electricity": "Elec.", "Electronic": "Elec.",
    "Employ": "Emp.", "Employee": "Emp.", "Employer": "Emp’r", "Employment": "Emp’t",
    "Engineer": "Eng’r", "Engineering": "Eng’g", "Enterprise": "Enter.",
    "Entertainment": "Entm’t", "Environment": "Env’t", "Environmental": "Env’t",
    "Equality": "Equal.", "Equipment": "Equip.", "Examiner": "Exam’r", "Exchange": "Exch.",
    "Executive": "Exec.", "Executor": "Ex’r", "Executrix": "Ex’x", "Exploration": "Expl.",
    "Exploratory": "Expl.", "Export": "Exp.", "Exportation": "Exp.", "Exporter": "Exp.",
    "Federal": "Fed.", "Federation": "Fed’n", "Fidelity": "Fid.", "Finance": "Fin.",
    "Financial": "Fin.", "Financing": "Fin.", "Foundation": "Found.", "General": "Gen.",
    "Global": "Glob.", "Government": "Gov’t", "Group": "Grp.", "Guaranty": "Guar.",
    "Hospital": "Hosp.", "Housing": "Hous.", "Human": "Hum.", "Immigration": "Immigr.",
    "Import": "Imp.", "Importation": "Imp.", "Importer": "Imp.", "Incorporated": "Inc.",
    "Indemnity": "Indem.", "Independence": "Indep.", "Independent": "Indep.",
    "Industry": "Indus.", "Industries": "Indus.", "Industrial": "Indus.", "Information": "Info.",
    "Injury": "Inj.", "Institute": "Inst.", "Institution": "Inst.", "Insurance": "Ins.",
    "Interest": "Int.", "International": "Int’l", "Investment": "Inv.", "Investor": "Inv.",
    "Labor": "Lab.", "Laboratory": "Lab.", "Liability": "Liab.", "Limited": "Ltd.",
    "Litigation": "Litig.", "Machine": "Mach.", "Machinery": "Mach.", "Maintenance": "Maint.",
    "Management": "Mgmt.", "Manufacturer": "Mfr.", "Manufacturing": "Mfg.", "Maritime": "Mar.",
    "Market": "Mkt.", "Marketing": "Mktg.", "Mechanic": "Mech.", "Mechanical": "Mech.",
    "Medical": "Med.", "Medicinal": "Med.", "Medicine": "Med.", "Memorial": "Mem’l",
    "Merchant": "Merch.", "Merchandise": "Merch.", "Merchandising": "Merch.",
    "Metropolitan": "Metro.", "Mortgage": "Mortg.", "Municipal": "Mun.", "Mutual": "Mut.",
    "National": "Nat’l", "Natural": "Nat.", "North": "N.", "Northern": "N.",
    "Northeast": "Ne.", "Northeastern": "Ne.", "Northwest": "Nw.",
    "Northwestern": "Nw.", "Number": "No.", "Office": "Off.", "Official": "Off.",
    "Opinion": "Op.", "Order": "Ord.", "Organization": "Org.", "Organizing": "Org.",
    "Pacific": "Pac.", "Parish": "Par.", "Partnership": "P’ship", "Person": "Pers.",
    "Personal": "Pers.", "Personnel": "Pers.", "Pharmaceutics": "Pharm.",
    "Pharmaceuticals": "Pharm.", "Political": "Pol.", "Politics": "Pol.",
    "Preserve": "Pres.", "Preservation": "Pres.", "Probate": "Prob.",
    "Probation": "Prob.", "Product": "Prod.", "Production": "Prod.",
    "Professional": "Prof’l", "Property": "Prop.", "Protection": "Prot.",
    "Public": "Pub.", "Publication": "Publ’n", "Publishing": "Publ’g",
    "Railroad": "R.R.", "Railway": "Ry.", "Record": "Rec.", "Recording": "Rec.",
    "Refining": "Ref.", "Regional": "Reg’l", "Register": "Reg.", "Regulation": "Regul.",
    "Regulator": "Regul.", "Regulatory": "Regul.", "Rehabilitation": "Rehab.",
    "Rehabilitative": "Rehab.", "Relation": "Rel.", "Reproduction": "Reprod.",
    "Reproductive": "Reprod.", "Research": "Rsch.", "Resource": "Res.",
    "Resources": "Res.", "Restaurant": "Rest.", "Retirement": "Ret.",
    "Rights": "Rts.", "Road": "Rd.", "Savings": "Sav.", "School": "Sch.",
    "Schools": "Sch.", "Science": "Sci.", "Scientific": "Sci.", "Secretary": "Sec’y",
    "Security": "Sec.", "Securities": "Sec.", "Service": "Serv.", "Shareholder": "S’holder",
    "Stockholder": "S’holder", "Social": "Soc.", "Society": "Soc’y", "Solution": "Sol.",
    "South": "S.", "Southern": "S.", "Southeast": "Se.", "Southeastern": "Se.",
    "Southwest": "Sw.", "Southwestern": "Sw.", "Steamship": "S.S.", "Steamships": "S.S.",
    "Street": "St.", "Subcommittee": "Subcomm.", "Surety": "Sur.", "System": "Sys.",
    "Systems": "Sys.", "Teacher": "Tchr.", "Technical": "Tech.",
    "Technological": "Tech.", "Technology": "Tech.", "Telecommunication": "Telecomm.",
    "Telephone": "Tel.", "Telegraph": "Tel.", "Temporary": "Temp.", "Township": "Twp.",
    "Transcontinental": "Transcon.", "Transport": "Transp.", "Transportation": "Transp.",
    "Trustee": "Tr.", "Uniform": "Unif.", "United": "U.S.", "States": "U.S.",
    "University": "Univ.", "Utility": "Util.", "Village": "Vill.", "West": "W.",
    "Western": "W."
}